#!/bin/bash

# Скрипт для демонстрации работы IoT Device Simulator

echo "🚀 IoT Device Simulator Demo"
echo "============================"
echo ""

# Показать справку
echo "1. Показать справку по использованию:"
echo "----------------------------------------"
node app/iot-device-simulator/dist/main.js --help 2>/dev/null || echo "Справка недоступна, используйте следующие параметры:"
echo ""
echo "🔧 Обязательные параметры:"
echo "  --user-id <id>        ID пользователя"
echo "  --device-id <id>      ID устройства"
echo ""
echo "🔧 Опциональные параметры:"
echo "  --mqtt-host <host>    MQTT брокер (по умолчанию: localhost)"
echo "  --mqtt-port <port>    MQTT порт (по умолчанию: 1883)"
echo "  --qos <0|1|2>         QoS уровень (по умолчанию: 1)"
echo ""

echo "2. Пример запуска:"
echo "-------------------"
echo "node app/iot-device-simulator/dist/main.js --user-id demo-user --device-id demo-device-001"
echo ""

echo "3. Пример с настройкой MQTT:"
echo "-----------------------------"
echo "node app/iot-device-simulator/dist/main.js \\"
echo "  --user-id demo-user \\"
echo "  --device-id demo-device-001 \\"
echo "  --mqtt-host broker.example.com \\"
echo "  --mqtt-port 1883 \\"
echo "  --qos 2"
echo ""

echo "4. Пример с mTLS:"
echo "------------------"
echo "node app/iot-device-simulator/dist/main.js \\"
echo "  --user-id demo-user \\"
echo "  --device-id demo-device-001 \\"
echo "  --use-tls true \\"
echo "  --cert-path ./certs/devices/working-device-cert.pem \\"
echo "  --key-path ./certs/devices/working-device-key.pem \\"
echo "  --ca-path ./certs/devices/ca-cert.pem"
echo ""

echo "📋 Функциональность симулятора:"
echo "-------------------------------"
echo "✅ Подключение к MQTT брокеру"
echo "✅ Симуляция датчиков (температура, влажность, давление)"
echo "✅ Обработка RPC команд через MQTT"
echo "✅ Управление таймерами (дискретные и аналоговые)"
echo "✅ Управление регуляторами (PID контроллеры)"
echo "✅ Управление ирригационными системами"
echo "✅ Поддержка mTLS аутентификации"
echo "✅ Автоматическое обновление данных сенсоров"
echo ""

echo "🔧 Команды для управления через Nx:"
echo "-----------------------------------"
echo "npx nx build iot-device-simulator    # Сборка приложения"
echo "npx nx test iot-device-simulator     # Запуск тестов"
echo "npx nx lint iot-device-simulator     # Проверка кода"
echo ""

echo "✨ Готово! Симулятор устройства создан и готов к использованию."
