FROM quay.io/keycloak/keycloak:latest AS builder
USER root
COPY keycloak/providers/ /opt/keycloak/providers/
COPY keycloak/keycloak-kafka.properties /opt/keycloak/conf/keycloak-kafka.properties
RUN /opt/keycloak/bin/kc.sh build --spi-events-listener--kafka--enabled=true

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/
USER keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--spi-events-listener--kafka--enabled=true","--features=quick-theme"]