receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
      - key: service.environment
        value: 'development'
        action: upsert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tenant_id: 'tenant-1'
    labels:
      resource:
        service.name: 'service_name'
        service.environment: 'service_environment'
      attributes:
        level: 'severity_text'
        traceid: 'trace_id'
        spanid: 'span_id'
    format: json
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [loki, debug]
